// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using SlickDealsNotifier;
using System;

namespace SlickDealsNotifier.Migrations
{
    [DbContext(typeof(SlickDealsNotifierContext))]
    [Migration("20180314042307_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("SlickDealsNotifier.Deal", b =>
                {
                    b.Property<int>("DealId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsFire");

                    b.Property<string>("Price");

                    b.Property<string>("Store");

                    b.Property<string>("Title");

                    b.Property<string>("Url");

                    b.Property<int>("Votes");

                    b.HasKey("DealId");

                    b.ToTable("Deals");
                });
#pragma warning restore 612, 618
        }
    }
}
